site_name: Linux Training for CIRT
site_description: Comprehensive Linux command line training for the CIRT team
site_author: IT Training Team
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Course Overview:
    - Introduction: overview/introduction.md
    - Prerequisites: overview/prerequisites.md
    - Course Structure: overview/structure.md
  - Modules:
    - "Module 1: Command Line Basics":
      - modules/01-command-line-basics/index.md
      - Introduction: modules/01-command-line-basics/01-introduction.md
      - Terminal Basics: modules/01-command-line-basics/02-terminal.md
      - Shell Basics: modules/01-command-line-basics/03-shell-basics.md
      - Navigation: modules/01-command-line-basics/04-navigation.md
      - Exercises: 
        - modules/01-command-line-basics/exercises/index.md
        - Basic Commands: modules/01-command-line-basics/exercises/basic-commands.md
        - Shell Navigation: modules/01-command-line-basics/exercises/shell-navigation.md
      - Labs:
        - Lab 1: modules/01-command-line-basics/labs/lab1-shell-basics.md
        - Lab 2: modules/01-command-line-basics/labs/lab2-navigation.md
    
    - "Module 2: File System Navigation":
      - modules/02-file-system/index.md
      - File System Hierarchy: modules/02-file-system/01-filesystem-hierarchy.md
      - File Types: modules/02-file-system/02-file-types.md
      - File Operations: modules/02-file-system/03-file-operations.md
      - Permissions: modules/02-file-system/04-permissions.md
      # Continue with exercises and labs...

    # Continue with other modules...

extra:
  social:
    - icon: fontawesome/brands/github
      link: # Your repo URL here
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: >
  Copyright &copy; 2024 IT Training Team –
  <a href="#__consent">Change cookie settings</a>